# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=10)),
                ('wheeler', models.CharField(max_length=5)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
            ],
        ),
    ]
