# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiclecount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.TextField(blank=True, db_column='Vehicle', null=True)),
                ('count', models.IntegerField(blank=True, db_column='Count', null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'VehicleCount',
            },
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
