# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0002_auto_20160423_1552'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehiclecount',
            table=None,
        ),
    ]
