# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0003_auto_20160423_1558'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehiclecount',
            table='VehicleCount',
        ),
    ]
