# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0005_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
