# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0009_auto_20160424_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
